name: main

on:
  push:
    paths:
      - 'mingw-w64-*/*'
  pull_request:
    paths:
      - 'mingw-w64-*/*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include: [
          { msystem: mingw32, toolchain: i686 },
          { msystem: mingw64, toolchain: x86_64 },
          { msystem: ucrt64, toolchain: ucrt-x86_64 }
        ]
      fail-fast: false
    defaults:
      run:
        shell: msys2 {0}
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: git
          update: true

      - name: CI-Build
        run: ./ci-build.sh
        env:
          BUILD_URL: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          MINGW_ARCH: ${{ matrix.msystem }}
          MINGW_TOOLCHAIN: ${{ matrix.toolchain }}
          PACMAN_REPOSITORY: ${{ matrix.msystem }}

      - name: "Upload binary package"
        uses: actions/upload-artifact@v2
        if: success() && (matrix.msystem == 'ucrt64' || !contains(github.event.head_commit.message, 'ucrt-only'))
        with:
          name: ${{ matrix.msystem }}
          path: artifacts/

      - name: "Upload source package"
        uses: actions/upload-artifact@v2
        if: success() && matrix.msystem == 'mingw64' && !contains(github.event.head_commit.message, 'ucrt-only')
        with:
          name: sources
          path: sourcepkg/

  deploy:
    name: Deploy to staging server
    runs-on: ubuntu-20.04
    needs: [build]
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Get artifacts for deployment
        uses: actions/download-artifact@v2
      - id: deployment
        name: Uploading files
        run: |
          ls -ltrR
          eval $(ssh-agent -s)
          ssh-add <(echo "$STAGINGKEY")
          echo 'put -pr .' | sftp -oStrictHostKeyChecking=no "${STAGINGUSER}@ftp.opencpu.org:/rtools"
          exit ${PIPESTATUS[1]}
        env:
          STAGINGUSER: ${{ secrets.STAGINGUSER }}
          STAGINGKEY: ${{ secrets.STAGINGKEY }}
